version: '3.8'
services:
  postgis:
    container_name: pg_container
    image: postgis/postgis
    env_file:
      - pg.env
    ports:
      - 5432:5432
    volumes:
      - local_pgdata:/var/lib/postgis/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    env_file:
      - pgadmin.env
    ports:
      - 5050:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: